In [146]:
import numpy as np 
import pandas as  pd

In [147]:
df = pd.read_csv("creditcard.csv")

In [148]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [149]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [150]:
df.shape

(284807, 31)

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [152]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [153]:
# upsampling

In [154]:
df_minority = df[df['Class']==1]
df_majority = df[df['Class']==0]

In [155]:
df_majority = df_majority.sample(100000,random_state=2)

In [156]:
df_majority.shape # resizing the datapoints to 1Lakhs

(100000, 31)

In [157]:
len(df_majority)

100000

In [158]:
## performing upsampling

In [159]:
from sklearn.utils import resample

In [160]:
df_minority_upsample = resample(df_minority,
                        replace=True ,
                       n_samples = len(df_majority), # want to match df_majority
                       random_state =2)

In [161]:
df_minority_upsample.shape

(100000, 31)

In [162]:
df_minority_upsample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
64460,51155.0,-11.205461,7.914633,-13.987752,4.333341,-8.484970,-3.506561,-8.935243,7.704449,-2.336584,...,0.942593,-0.987848,-0.279446,-0.027299,0.644344,-0.263078,1.084023,0.211933,99.99,1
6717,8408.0,-1.813280,4.917851,-5.926130,5.701500,1.204393,-3.035138,-1.713402,0.561257,-3.796354,...,0.615642,-0.406427,-0.737018,-0.279642,1.106766,0.323885,0.894767,0.569519,1.00,1
15810,27252.0,-25.942434,14.601998,-27.368650,6.378395,-19.104033,-4.684806,-18.261393,17.052566,-3.742605,...,1.784316,-1.917759,-1.235787,0.161105,1.820378,-0.219359,1.388786,0.406810,99.99,1
6899,8878.0,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00,1
150662,93853.0,-5.839192,7.151532,-12.816760,7.031115,-9.651272,-2.938427,-11.543207,4.843627,-3.494276,...,2.462056,1.054865,0.530481,0.472670,-0.275998,0.282435,0.104886,0.254417,316.06,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151519,95628.0,-17.518909,12.572118,-19.038538,11.190895,-13.554721,-0.411924,-23.189397,-5.301412,-8.630390,...,-4.969478,0.976125,1.841248,0.334418,-0.720128,-0.232603,-3.021992,-0.478158,1.63,1
150697,93920.0,-12.381048,8.213022,-16.962530,7.116091,-9.772826,-3.666836,-16.147363,2.078706,-4.250657,...,0.167703,1.503413,-0.767755,0.371951,-1.415639,-0.517022,-0.434621,0.292721,97.00,1
95597,65385.0,-2.923827,1.524837,-3.018758,3.289291,-5.755542,2.218276,-0.509995,-3.569444,-1.016592,...,-0.511657,-0.122724,-4.288639,0.563797,-0.949451,-0.204532,1.510206,-0.324706,1354.25,1
276071,166883.0,2.091900,-0.757459,-1.192258,-0.755458,-0.620324,-0.322077,-1.082511,0.117200,-0.140927,...,0.288253,0.831939,0.142007,0.592615,-0.196143,-0.136676,0.020182,-0.015470,19.95,1
108258,70828.0,0.196707,1.189757,0.704882,2.891388,0.045555,1.245730,-1.198714,-2.421616,-1.232089,...,-1.328132,0.189311,-0.005524,-0.814708,0.400924,0.286281,0.135215,0.257315,0.76,1

In [163]:
df_minority_upsample['Class'].value_counts()

1    100000
Name: Class, dtype: int64

In [164]:
# after upsampling our new dataframe
new_df= pd.concat([df_minority_upsample,df_majority])

In [165]:
new_df.shape

(200000, 31)

In [166]:
new_df = new_df.reset_index(drop=True)

In [167]:
new_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,51155.0,-11.205461,7.914633,-13.987752,4.333341,-8.484970,-3.506561,-8.935243,7.704449,-2.336584,...,0.942593,-0.987848,-0.279446,-0.027299,0.644344,-0.263078,1.084023,0.211933,99.99,1
1,8408.0,-1.813280,4.917851,-5.926130,5.701500,1.204393,-3.035138,-1.713402,0.561257,-3.796354,...,0.615642,-0.406427,-0.737018,-0.279642,1.106766,0.323885,0.894767,0.569519,1.00,1
2,27252.0,-25.942434,14.601998,-27.368650,6.378395,-19.104033,-4.684806,-18.261393,17.052566,-3.742605,...,1.784316,-1.917759,-1.235787,0.161105,1.820378,-0.219359,1.388786,0.406810,99.99,1
3,8878.0,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00,1
4,93853.0,-5.839192,7.151532,-12.816760,7.031115,-9.651272,-2.938427,-11.543207,4.843627,-3.494276,...,2.462056,1.054865,0.530481,0.472670,-0.275998,0.282435,0.104886,0.254417,316.06,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,133789.0,1.871381,-0.654491,-0.390061,0.326718,-0.619596,0.051022,-0.700735,0.113892,0.995999,...,0.224153,0.746056,0.065202,-0.399706,-0.284328,0.573093,-0.027957,-0.052685,57.50,0
199996,151525.0,-0.048303,1.651313,0.975766,4.156477,1.187089,1.263794,0.648676,0.001291,-2.153696,...,0.067869,0.325440,-0.123803,0.118573,-0.452730,0.300346,0.087792,0.182741,8.04,0
199997,84479.0,-1.324393,1.015700,0.883987,0.156518,-0.103071,-1.004786,0.143101,-0.634094,-0.064265,...,0.421779,-0.983601,0.482864,0.280533,-0.097229,0.065357,-0.042024,-0.254298,8.98,0
199998,150567.0,1.965765,-0.409780,-0.226305,0.524378,-0.789315,-0.535147,-0.607055,-0.043530,1.456585,...,0.200804,0.848655,0.125023,0.014192,-0.109649,-0.210343,0.045422,-0.036637,9.99,0
199999,151152.0,1.856666,-1.436234,-0.967593,-1.258818,-0.087987,1.735918,-1.219986,0.535428,-0.177015,...,0.098054,0.116745,0.321571,-0.965369,-0.664708,-0.414423,0.034977,-0.043495,109.00,0

In [168]:
new_df['Class'].value_counts()

1    100000
0    100000
Name: Class, dtype: int64

In [169]:
# our 50% class =1 and 50% class =0 data is perfectly balanced

In [170]:
# checking the null values

In [171]:
new_df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [172]:
# there is no null values

In [173]:
X=new_df.drop(labels=["Class"],axis=1)

In [174]:
X.shape

(200000, 30)

In [175]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,51155.0,-11.205461,7.914633,-13.987752,4.333341,-8.484970,-3.506561,-8.935243,7.704449,-2.336584,...,0.860912,0.942593,-0.987848,-0.279446,-0.027299,0.644344,-0.263078,1.084023,0.211933,99.99
1,8408.0,-1.813280,4.917851,-5.926130,5.701500,1.204393,-3.035138,-1.713402,0.561257,-3.796354,...,0.576656,0.615642,-0.406427,-0.737018,-0.279642,1.106766,0.323885,0.894767,0.569519,1.00
2,27252.0,-25.942434,14.601998,-27.368650,6.378395,-19.104033,-4.684806,-18.261393,17.052566,-3.742605,...,1.667304,1.784316,-1.917759,-1.235787,0.161105,1.820378,-0.219359,1.388786,0.406810,99.99
3,8878.0,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.399097,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00
4,93853.0,-5.839192,7.151532,-12.816760,7.031115,-9.651272,-2.938427,-11.543207,4.843627,-3.494276,...,0.055684,2.462056,1.054865,0.530481,0.472670,-0.275998,0.282435,0.104886,0.254417,316.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,133789.0,1.871381,-0.654491,-0.390061,0.326718,-0.619596,0.051022,-0.700735,0.113892,0.995999,...,-0.064855,0.224153,0.746056,0.065202,-0.399706,-0.284328,0.573093,-0.027957,-0.052685,57.50
199996,151525.0,-0.048303,1.651313,0.975766,4.156477,1.187089,1.263794,0.648676,0.001291,-2.153696,...,0.278329,0.067869,0.325440,-0.123803,0.118573,-0.452730,0.300346,0.087792,0.182741,8.04
199997,84479.0,-1.324393,1.015700,0.883987,0.156518,-0.103071,-1.004786,0.143101,-0.634094,-0.064265,...,-0.362554,0.421779,-0.983601,0.482864,0.280533,-0.097229,0.065357,-0.042024,-0.254298,8.98
199998,150567.0,1.965765,-0.409780,-0.226305,0.524378,-0.789315,-0.535147,-0.607055,-0.043530,1.456585,...,-0.223244,0.200804,0.848655,0.125023,0.014192,-0.109649,-0.210343,0.045422,-0.036637,9.99
199999,151152.0,1.856666,-1.436234,-0.967593,-1.258818,-0.087987,1.735918,-1.219986,0.535428,-0.177015,...,0.141057,0.098054,0.116745,0.321571,-0.965369,-0.664708,-0.414423,0.034977,-0.043495,109.00

In [176]:
y=new_df["Class"]

In [177]:
y.shape

(200000,)

In [178]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Class, dtype: int64

In [179]:
from sklearn.model_selection import train_test_split

In [180]:
#we did train and test split before only why because we dont want data leakage
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25,random_state=50)

In [181]:
#preprocessing steps
from sklearn.preprocessing import StandardScaler
train_scaler=StandardScaler()
test_scaler=StandardScaler()

In [182]:
X_train_scaled=train_scaler.fit_transform(X_train)

In [183]:
X_test_scaled=train_scaler.transform(X_test)

In [184]:
from sklearn.ensemble import RandomForestClassifier

# Create an instance of the RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=10, random_state=42)

# Fit the model to your data
rf_classifier.fit(X_train_scaled, y_train)

# Make predictions
predictions = rf_classifier.predict(X_test)

C:\Users\Asmit\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [187]:
y_pred = predictions

In [188]:
y_pred

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [189]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [190]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[24015  7821]
 [  952 17212]]
0.82454
              precision    recall  f1-score   support

           0       0.96      0.75      0.85     31836
           1       0.69      0.95      0.80     18164

    accuracy                           0.82     50000
   macro avg       0.82      0.85      0.82     50000
weighted avg       0.86      0.82      0.83     50000

In [191]:
# accuracy = 0.82%